LOCAL_GOOGLE_API_KEY=AIzaSyDFYyzg_yLCaYsllhXI7ycfscNAcoq61ko
DEV_GOOGLE_API_KEY=AIzaSyBWibr3JC0TxK-Mwn2nYKCGs3xpew1Vokg
UAT_GOOGLE_API_KEY=AIzaSyD9RfytKcML5bY0OyFAfo20W4Nsyc_ekqk
PROD_GOOGLE_API_KEY=AIzaSyBvDiQYPTbdTBSRcbayaXDIDCbe-j9pBmM